# Travis CI build file for swift-ubuntu image.
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

language: generic

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "VFUQIBCL8Kiubw7ojN3oJOs2TgobYaAZTCQePDATOMSRKRo/rDgsloGDc3kqGkLb0lAwky1lwKQjnRUsG1mEES6+W2K3QWsmzpTR1owPzZprrHrL/h1vkWdysx7ed0dBnbs8uhtD4iPe46vWZqLc1ZyfV8QxefTD9mrS4VeH7rd4qOwMgkjphaoVc0/cOkt0u8p54961HLVt4euSZf0766hfYH+1EwvoShaiK/2aKTF/hmFavB2iASHRXJnOm9S4iDWyFW2D7XEwoo9o9jOAqtYbVefGglCjUymmuNCmj1bE3NSWXJB/5KC8xFNYs7b5jZ19diu5PQK2K1HCtJvLhW2wv7cBfBFrluvz52zeHB8izYIiSV+sr6mJgnPuwaoYUObJWkLlKpTo3oPgAU/62l0KMgdn1EoBrCSDVCz5IBjLmty25nFl1oDGZITQjNIkIMUjh4dojjr+JSRDumHxje39bu8nvxsA5pxDulnWQNorvaHeWf8t2ZAqYW/ojpAlmvBr7E+U9P6DHw40FDStcI8bJGfWv8yybjMocYtTTl6FaQdfqNm3Afp5wlUxNAkAG2neRGnuitHTQ4CBHquA9NG4c7tlyafUf9UMuce3ikQiUeecNnrW2tLkKEnkO6KXwgvOCAyQrFMHncPWXfQVY/+c/2ejelCOUW8BL2pBLBY="

sudo: required
services: docker

# after_success failure doesn't fail build: https://github.com/travis-ci/travis-ci/issues/758
script:
  - docker build --pull -t ibmcom/ubuntu:14.04 ./ibm-ubuntu
  - docker build -t ibmcom/swift-ubuntu:latest ./swift-dev
  - docker build -t ibmcom/swift-runtime:latest ./swift-runtime
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
      docker push ibmcom/ubuntu:14.04;
      docker push ibmcom/swift-ubuntu:latest;
      docker push ibmcom/swift-runtime:latest;
    fi
